%==========================================================================
%Given a list of niftis generated by generateRandomNiftis, select a subset
%of them in a biased manor.
%
%Authors: Thomas Maullin
%==========================================================================

function struct = biasSelect(CElist, CSElist, XYZ)
    
    valueArray = [];
    valueSEArray = [];
    for i = 1:length(CElist)
        
        vol       = spm_vol(CElist{i});
        
        img1 = spm_slice_vol(vol,spm_matrix([0 0 (XYZ(3)-1)]),vol.dim(1:2),0);
        img2 = spm_slice_vol(vol,spm_matrix([0 0 (XYZ(3))]),vol.dim(1:2),0);
        img3 = spm_slice_vol(vol,spm_matrix([0 0 (XYZ(3)+1)]),vol.dim(1:2),0);
        
        
        volume = spm_read_vols(vol);
        imgMean = mean(abs(volume(volume ~= 0 & ~isnan(volume))));
        if imgMean > 10
            disp('active')
            img1=img1./100;
            img2=img2./100;
            img3=img3./100;
        end
        
        obsVal = [img1((XYZ(1)-1):(XYZ(1)+1), (XYZ(2)-1):(XYZ(2)+1)),...
                  img2((XYZ(1)-1):(XYZ(1)+1), (XYZ(2)-1):(XYZ(2)+1)),...
                  img3((XYZ(1)-1):(XYZ(1)+1), (XYZ(2)-1):(XYZ(2)+1))];
        
        valueArray(i) = mean(mean(obsVal));
        
        vol       = spm_vol(CSElist{i});
        
        img1 = spm_slice_vol(vol,spm_matrix([0 0 (XYZ(3)-1)]),vol.dim(1:2),0);
        img2 = spm_slice_vol(vol,spm_matrix([0 0 (XYZ(3))]),vol.dim(1:2),0);
        img3 = spm_slice_vol(vol,spm_matrix([0 0 (XYZ(3)+1)]),vol.dim(1:2),0);
        
        if imgMean > 10
            disp('active')
            img1=img1./100;
            img2=img2./100;
            img3=img3./100;
        end
        
        obsVal = [img1((XYZ(1)-1):(XYZ(1)+1), (XYZ(2)-1):(XYZ(2)+1)),...
                  img2((XYZ(1)-1):(XYZ(1)+1), (XYZ(2)-1):(XYZ(2)+1)),...
                  img3((XYZ(1)-1):(XYZ(1)+1), (XYZ(2)-1):(XYZ(2)+1))];
        
        valueSEArray(i) = mean(mean(obsVal));
        
    end
        
    [val, ranks] = sort(valueArray);
    disp(val)
    output1 = {CElist{ranks}};
    output2 = {CSElist{ranks}};
    
    alternateRanks = randi([1,21], 1, 14)
    struct = {{output1{14:21}}, {output2{14:21}}, {output1{1:8}}, {output2{1:8}}};
    
end